### ISSUE TITLE
Enable creating `ipset::set` resources via Hiera

### ISSUE THREAD

**Issue by kBite** [voxpupuli/puppet-ipset#41]
Enable creating `ipset::set` resources via Hiera.

Example: 'puppet-ferm' enables creating e.g. `ferm::rule` resources via Hiera (https://github.com/voxpupuli/puppet-ferm).

**Comment by titleistfour** [comment]
This would be very handy.  Can this be merged in?

**Comment by kBite** [comment]
@titleistfour Seems this issue wasn't closed properly. The feature itself is already merged, see [manifests/init.pp#L24](https://github.com/voxpupuli/puppet-ipset/blob/a78c1ac64959ae7d154af3d5c9f5f6ef2f3cef95/manifests/init.pp#L24)
